url: "http://gouravanvekar.com"
baseurl: 

# Site settings
title: Gaurav Anvekar
email: gaurav.anvekar@live.com
description: "Gaurav is a passionate full stack web developer with hands-on experience in end to end web applications development. His current and recent projects include some of the trending web features implemented using responsive web design techniques, SEO, business intelligence and web analytics."

# Color settings
color:
  primary: 3498db
  secondary: 246D9E  
  secondary-dark: 333

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/gouravanvekar
  - title: facebook
    url: https://www.facebook.com/gaurav.anvekar7
  - title: google-plus
    url: https://plus.google.com/+GouravAnvekar
  - title: linkedin 
    url: https://www.linkedin.com/in/gouravanvekar
  - title: github
    url: http://github.com/gouravanvekar

# Postal address
address:
  - line: 880 Carillon Parkway
  - line: St. Petersburg, FL 33716

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8